#ifndef __FILE_MERGER_H__
#define __FILE_MERGER_H__

/* This file is automatically generated by G+ FileMerger.
   Do not modify the contents to prevent from invalid addressing.
*/ 

#if defined (__GNUC__) || defined (__CC_ARM)  || defined (__ICCARM__) 	/* 32 bit ARM compiler */

	#include <stdint.h>
	#if defined (__CSRC_USED__)					/* use C source instead of elf obj file */
		extern const uint8_t* FileMerger_ROM_bin_Data;
		#define SEC_START_ADDR FileMerger_ROM_bin_Data
	#else
		extern uint8_t _binary_FileMerger_ROM_bin_start;
		extern uint32_t _binary_FileMerger_ROM_bin_size;

		#define SEC_START_ADDR &_binary_FileMerger_ROM_bin_start
	#endif

#else
	#define SEC_START_ADDR 0
#endif

#define _GROUP_TABLE                   0       	//Group Index:0           Group Name:Group_Table     Group Type:Unknown 
#define _GROUP_TABLE_ADDR              (SEC_START_ADDR + 0x00000c)	//Group Addr :0x00000c    Group Name:Group_Table     Group Type:Unknown 
#define _GOLD                          0       	//File  Index:0           File  Name:gold.a18 
#define _GOLD_ADDR                     (SEC_START_ADDR + 0x00000c)	//File  Addr :0x00000c    File  Name:gold.a18 
#define _DIDI                          1       	//File  Index:1           File  Name:didi.a18 
#define _DIDI_ADDR                     (SEC_START_ADDR + 0x001cd2)	//File  Addr :0x001cd2    File  Name:didi.a18 

#endif /* __FILE_MERGER_H__ */
