#ifndef __FILE_MERGER_H__
#define __FILE_MERGER_H__

/* This file is automatically generated by G+ FileMerger.
   Do not modify the contents to prevent from invalid addressing.
*/ 

#if defined (__GNUC__) || defined (__CC_ARM)	/* 32 bit ARM compiler */

	#include <stdint.h>
	#if defined (__CSRC_USED__)					/* use C source instead of elf obj file */
		extern const uint8_t* ROM_bin_Data;
		#define SEC_START_ADDR ROM_bin_Data
	#else
		extern uint8_t _binary_ROM_bin_start;
		extern uint32_t _binary_ROM_bin_size;

		#define SEC_START_ADDR &_binary_ROM_bin_start
	#endif

#else
	#define SEC_START_ADDR 0
#endif

#define _GROUP_TABLE                   0       	//Group Index:0           Group Name:Group_Table     Group Type:Unknown 
#define _GROUP_TABLE_ADDR              (SEC_START_ADDR + 0x000190)	//Group Addr :0x000190    Group Name:Group_Table     Group Type:Unknown 
#define _TTBIN_128M                    0       	//File  Index:0           File  Name:TTbin_128m.bin 
#define _TTBIN_128M_ADDR               (SEC_START_ADDR + 0x000190)	//File  Addr :0x000190    File  Name:TTbin_128m.bin 
#define _TAILOR3_16K                   1       	//File  Index:1           File  Name:tailor3_16K.a18 
#define _TAILOR3_16K_ADDR              (SEC_START_ADDR + 0xfff380)	//File  Addr :0xfff380    File  Name:tailor3_16K.a18 
#define _SONG03                        2       	//File  Index:2           File  Name:song03.a18 
#define _SONG03_ADDR                   (SEC_START_ADDR + 0x1017896)	//File  Addr :0x1017896    File  Name:song03.a18 
#define _SONG02                        3       	//File  Index:3           File  Name:song02.a18 
#define _SONG02_ADDR                   (SEC_START_ADDR + 0x101e1bc)	//File  Addr :0x101e1bc    File  Name:song02.a18 
#define _SONG01                        4       	//File  Index:4           File  Name:song01.a18 
#define _SONG01_ADDR                   (SEC_START_ADDR + 0x102f27c)	//File  Addr :0x102f27c    File  Name:song01.a18 
#define _RS10YRZM                      5       	//File  Index:5           File  Name:rs10yrzm.a18 
#define _RS10YRZM_ADDR                 (SEC_START_ADDR + 0x1037fde)	//File  Addr :0x1037fde    File  Name:rs10yrzm.a18 
#define _RS09BGPS                      6       	//File  Index:6           File  Name:rs09bgps.a18 
#define _RS09BGPS_ADDR                 (SEC_START_ADDR + 0x103927c)	//File  Addr :0x103927c    File  Name:rs09bgps.a18 
#define _RS08ZBLWJSLEEP                7       	//File  Index:7           File  Name:rs08zblwjsleep.a18 
#define _RS08ZBLWJSLEEP_ADDR           (SEC_START_ADDR + 0x103de62)	//File  Addr :0x103de62    File  Name:rs08zblwjsleep.a18 
#define _E4_16K                        8       	//File  Index:8           File  Name:e4_16K.a18 
#define _E4_16K_ADDR                   (SEC_START_ADDR + 0x104169e)	//File  Addr :0x104169e    File  Name:e4_16K.a18 
#define _E3_16K                        9       	//File  Index:9           File  Name:e3_16K.a18 
#define _E3_16K_ADDR                   (SEC_START_ADDR + 0x1041b7c)	//File  Addr :0x1041b7c    File  Name:e3_16K.a18 
#define _E2_16K                        10      	//File  Index:10          File  Name:e2_16K.a18 
#define _E2_16K_ADDR                   (SEC_START_ADDR + 0x1041f92)	//File  Addr :0x1041f92    File  Name:e2_16K.a18 
#define _E1_16K                        11      	//File  Index:11          File  Name:e1_16K.a18 
#define _E1_16K_ADDR                   (SEC_START_ADDR + 0x1042308)	//File  Addr :0x1042308    File  Name:e1_16K.a18 
#define _3DJT16K_GEA                   12      	//File  Index:12          File  Name:3Djt16k_gea.a18 
#define _3DJT16K_GEA_ADDR              (SEC_START_ADDR + 0x104276e)	//File  Addr :0x104276e    File  Name:3Djt16k_gea.a18 
#define _TBASIDETOSIDE                 13      	//File  Index:13          File  Name:TBasidetoside.sp4 
#define _TBASIDETOSIDE_ADDR            (SEC_START_ADDR + 0x104421c)	//File  Addr :0x104421c    File  Name:TBasidetoside.sp4 
#define _SPECIAL61_34K                 14      	//File  Index:14          File  Name:special61_34K.sp4 
#define _SPECIAL61_34K_ADDR            (SEC_START_ADDR + 0x10566f0)	//File  Addr :0x10566f0    File  Name:special61_34K.sp4 
#define _SPECIAL59_34K                 15      	//File  Index:15          File  Name:special59_34K.sp4 
#define _SPECIAL59_34K_ADDR            (SEC_START_ADDR + 0x10578fa)	//File  Addr :0x10578fa    File  Name:special59_34K.sp4 
#define _SPECIAL54_34K                 16      	//File  Index:16          File  Name:special54_34K.sp4 
#define _SPECIAL54_34K_ADDR            (SEC_START_ADDR + 0x1057e86)	//File  Addr :0x1057e86    File  Name:special54_34K.sp4 
#define _SPECIAL49_34K                 17      	//File  Index:17          File  Name:special49_34K.sp4 
#define _SPECIAL49_34K_ADDR            (SEC_START_ADDR + 0x1059278)	//File  Addr :0x1059278    File  Name:special49_34K.sp4 
#define _SPECIAL41_34K                 18      	//File  Index:18          File  Name:special41_34K.sp4 
#define _SPECIAL41_34K_ADDR            (SEC_START_ADDR + 0x105a35c)	//File  Addr :0x105a35c    File  Name:special41_34K.sp4 
#define _SPECIAL37_34K                 19      	//File  Index:19          File  Name:special37_34K.sp4 
#define _SPECIAL37_34K_ADDR            (SEC_START_ADDR + 0x105c882)	//File  Addr :0x105c882    File  Name:special37_34K.sp4 
#define _SPECIAL15_34K                 20      	//File  Index:20          File  Name:special15_34K.sp4 
#define _SPECIAL15_34K_ADDR            (SEC_START_ADDR + 0x105e1d8)	//File  Addr :0x105e1d8    File  Name:special15_34K.sp4 
#define _DI_12K_WAV                    21      	//File  Index:21          File  Name:di_12K_wav.sp4 
#define _DI_12K_WAV_ADDR               (SEC_START_ADDR + 0x105f158)	//File  Addr :0x105f158    File  Name:di_12K_wav.sp4 
#define _ANIMALS08_34K                 22      	//File  Index:22          File  Name:animals08_34K.sp4 
#define _ANIMALS08_34K_ADDR            (SEC_START_ADDR + 0x105f9b4)	//File  Addr :0x105f9b4    File  Name:animals08_34K.sp4 
#define _ANIMALS03_34K                 23      	//File  Index:23          File  Name:animals03_34K.sp4 
#define _ANIMALS03_34K_ADDR            (SEC_START_ADDR + 0x1061d0e)	//File  Addr :0x1061d0e    File  Name:animals03_34K.sp4 
#define _ANIMALS02_34K                 24      	//File  Index:24          File  Name:animals02_34K.sp4 
#define _ANIMALS02_34K_ADDR            (SEC_START_ADDR + 0x10637a4)	//File  Addr :0x10637a4    File  Name:animals02_34K.sp4 

#endif /* __FILE_MERGER_H__ */
