_Group_Table                      .equ    0       	;Group Index:0           Group Name:Group_Table     Group Type:Unknown 
_Group_Table_Addr                 .equ    0x000190	;Group Addr :0x000190    Group Name:Group_Table     Group Type:Unknown 
_TTbin_128m                       .equ    0       	;File  Index:0           File  Name:TTbin_128m.bin 
_TTbin_128m_Addr                  .equ    0x000190	;File  Addr :0x000190    File  Name:TTbin_128m.bin 
_tailor3_16K                      .equ    1       	;File  Index:1           File  Name:tailor3_16K.a18 
_tailor3_16K_Addr                 .equ    0xfff380	;File  Addr :0xfff380    File  Name:tailor3_16K.a18 
_song03                           .equ    2       	;File  Index:2           File  Name:song03.a18 
_song03_Addr                      .equ    0x1017896	;File  Addr :0x1017896    File  Name:song03.a18 
_song02                           .equ    3       	;File  Index:3           File  Name:song02.a18 
_song02_Addr                      .equ    0x101e1bc	;File  Addr :0x101e1bc    File  Name:song02.a18 
_song01                           .equ    4       	;File  Index:4           File  Name:song01.a18 
_song01_Addr                      .equ    0x102f27c	;File  Addr :0x102f27c    File  Name:song01.a18 
_rs10yrzm                         .equ    5       	;File  Index:5           File  Name:rs10yrzm.a18 
_rs10yrzm_Addr                    .equ    0x1037fde	;File  Addr :0x1037fde    File  Name:rs10yrzm.a18 
_rs09bgps                         .equ    6       	;File  Index:6           File  Name:rs09bgps.a18 
_rs09bgps_Addr                    .equ    0x103927c	;File  Addr :0x103927c    File  Name:rs09bgps.a18 
_rs08zblwjsleep                   .equ    7       	;File  Index:7           File  Name:rs08zblwjsleep.a18 
_rs08zblwjsleep_Addr              .equ    0x103de62	;File  Addr :0x103de62    File  Name:rs08zblwjsleep.a18 
_e4_16K                           .equ    8       	;File  Index:8           File  Name:e4_16K.a18 
_e4_16K_Addr                      .equ    0x104169e	;File  Addr :0x104169e    File  Name:e4_16K.a18 
_e3_16K                           .equ    9       	;File  Index:9           File  Name:e3_16K.a18 
_e3_16K_Addr                      .equ    0x1041b7c	;File  Addr :0x1041b7c    File  Name:e3_16K.a18 
_e2_16K                           .equ    10      	;File  Index:10          File  Name:e2_16K.a18 
_e2_16K_Addr                      .equ    0x1041f92	;File  Addr :0x1041f92    File  Name:e2_16K.a18 
_e1_16K                           .equ    11      	;File  Index:11          File  Name:e1_16K.a18 
_e1_16K_Addr                      .equ    0x1042308	;File  Addr :0x1042308    File  Name:e1_16K.a18 
_3Djt16k_gea                      .equ    12      	;File  Index:12          File  Name:3Djt16k_gea.a18 
_3Djt16k_gea_Addr                 .equ    0x104276e	;File  Addr :0x104276e    File  Name:3Djt16k_gea.a18 
_TBasidetoside                    .equ    13      	;File  Index:13          File  Name:TBasidetoside.sp4 
_TBasidetoside_Addr               .equ    0x104421c	;File  Addr :0x104421c    File  Name:TBasidetoside.sp4 
_special61_34K                    .equ    14      	;File  Index:14          File  Name:special61_34K.sp4 
_special61_34K_Addr               .equ    0x10566f0	;File  Addr :0x10566f0    File  Name:special61_34K.sp4 
_special59_34K                    .equ    15      	;File  Index:15          File  Name:special59_34K.sp4 
_special59_34K_Addr               .equ    0x10578fa	;File  Addr :0x10578fa    File  Name:special59_34K.sp4 
_special54_34K                    .equ    16      	;File  Index:16          File  Name:special54_34K.sp4 
_special54_34K_Addr               .equ    0x1057e86	;File  Addr :0x1057e86    File  Name:special54_34K.sp4 
_special49_34K                    .equ    17      	;File  Index:17          File  Name:special49_34K.sp4 
_special49_34K_Addr               .equ    0x1059278	;File  Addr :0x1059278    File  Name:special49_34K.sp4 
_special41_34K                    .equ    18      	;File  Index:18          File  Name:special41_34K.sp4 
_special41_34K_Addr               .equ    0x105a35c	;File  Addr :0x105a35c    File  Name:special41_34K.sp4 
_special37_34K                    .equ    19      	;File  Index:19          File  Name:special37_34K.sp4 
_special37_34K_Addr               .equ    0x105c882	;File  Addr :0x105c882    File  Name:special37_34K.sp4 
_special15_34K                    .equ    20      	;File  Index:20          File  Name:special15_34K.sp4 
_special15_34K_Addr               .equ    0x105e1d8	;File  Addr :0x105e1d8    File  Name:special15_34K.sp4 
_di_12K_wav                       .equ    21      	;File  Index:21          File  Name:di_12K_wav.sp4 
_di_12K_wav_Addr                  .equ    0x105f158	;File  Addr :0x105f158    File  Name:di_12K_wav.sp4 
_animals08_34K                    .equ    22      	;File  Index:22          File  Name:animals08_34K.sp4 
_animals08_34K_Addr               .equ    0x105f9b4	;File  Addr :0x105f9b4    File  Name:animals08_34K.sp4 
_animals03_34K                    .equ    23      	;File  Index:23          File  Name:animals03_34K.sp4 
_animals03_34K_Addr               .equ    0x1061d0e	;File  Addr :0x1061d0e    File  Name:animals03_34K.sp4 
_animals02_34K                    .equ    24      	;File  Index:24          File  Name:animals02_34K.sp4 
_animals02_34K_Addr               .equ    0x10637a4	;File  Addr :0x10637a4    File  Name:animals02_34K.sp4 
