_Group_Table:                     .equ    0       	;Group Index:0           Group Name:Group_Table     Group Type:Unknown 
_Group_Table_Addr:                .equ    0x00000c	;Group Addr :0x00000c    Group Name:Group_Table     Group Type:Unknown 
_didi:                            .equ    0       	;File  Index:0           File  Name:didi.a18 
_didi_Addr:                       .equ    0x00000c	;File  Addr :0x00000c    File  Name:didi.a18 
