//==========================================================================
// File Name   : R1800.inc
// Description : SACM R1800 API declaration
// Written by  : Ray Cheng
// Last modified date:
//              2005/12/26
//==========================================================================
.ifndef __R1800_INC__
.define __R1800_INC__

.external F_SACM_R1800_Initial
.external F_SACM_R1800_Rec
.external F_SACM_R1800_Stop
.external F_SACM_R1800_Status
.external F_SACM_R1800_ServiceLoop

.endif
//========================================================================================        
// End of SACM_R1800.inc
//========================================================================================