//==========================================================================
// File Name   : Touch_Probe.inc
// Description : Touch Probe Library API declaration
// Written by  : Ray Cheng
// Last modified date:
//              2012/10/24
//==========================================================================
.ifndef __Touch_Probe_INC__
.define __Touch_Probe_INC__

.external F_TP_Initial
.external F_TP_Start
.external F_TP_Stop
.external F_TP_ChangeCommand
.external F_TP_ServiceLoop

.endif
//========================================================================================        
// End of Touch.inc
//========================================================================================