//==========================================================================
// File Name   : RTVC.inc
// Description : SACM VC API declaration
// Written by  : Ray Cheng
// Last modified date:
//              2005/12/26
//==========================================================================
.ifndef __VC4_INC__
.define __VC4_INC__

.external F_SACM_VC4_Initial
.external F_SACM_VC4_Play
.external F_SACM_VC4_Stop
.external F_SACM_VC4_Volume
.external F_SACM_VC4_Pause
.external F_SACM_VC4_Resume
.external F_SACM_VC4_Status
.external F_SACM_VC4_ServiceLoop
.external F_ISR_Service_SACM_VC4
.external F_SACM_VC4_Mode;
.external F_SACM_VC4_DA_FIRType

.endif
//========================================================================================        
// End of RTVC.inc
//========================================================================================