//==========================================================================
// File Name   : VolCompr.inc
// Description : Volume Compressor APIs declaration
// Written by  : Benjamin Xu
// Last modified date:
//              2021/03/23
//==========================================================================

.external F_VolCompressInitial
.external F_SetVolCompressLevel
.external F_VolCompressProcess

//========================================================================================        
// End of System.inc
//========================================================================================